source 'https://rubygems.org'

gem 'rails', '6.1.7.9'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'
gem 'sqlite3'
gem 'ar-octopus', '0.6.0'
gem 'pry'

group :test do
  gem 'capybara'
  gem 'cucumber-rails', '>= 1.4.3', :require => false
  gem 'launchy'
  gem 'rspec-rails'
  gem 'aruba'
  gem 'database_cleaner'
end
